# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='s_descr',
            new_name='m_descr',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='s_fname',
            new_name='m_fname',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='s_join_date',
            new_name='m_join_date',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='s_lname',
            new_name='m_lname',
        ),
    ]
